### ISSUE TITLE
No context/line numbers reported on failure

### ISSUE THREAD

**Issue by TimeForAChange** [domenic/chai-as-promised#118]
I get a context and file and line-number reported by the normal chai rules but not when it's a chai-as-promised rule. the only link I found was an unanswered question on SO (http://stackoverflow.com/questions/30427192/when-using-chai-as-promised-can-you-get-a-line-number-w-the-failed-assertion).

**Comment by domenic** [comment]
Can you produce a small example file, using only the libraries chai and chai-as-promised (no test runners please), showing the comparison and what you perceive to be the problem?

**Comment by TimeForAChange** [comment]
Before I do that the question: is it supposed to? See screenshot. Failing test 1 is a normal chai test. Failing tests 2 and 3 are chai-as-promises tests. As you can see the chai test has context and line number information.

![unbenannt-1](https://cloud.githubusercontent.com/assets/199179/9292985/8b071f44-4416-11e5-9566-313eee7a4888.png)

**Comment by domenic** [comment]
I don't know. I haven't ever used a test runner that exposes information in that way. That's why I'm asking for a repro that is test-runner independent.

**Comment by TimeForAChange** [comment]
I can't do that because I don't know what that means :(

**Comment by keithamus** [comment]
@TimeForAChange if you could show us the code you've written that gives you the above error message, or if you can't, write some new code that still has the same issue. [This article on writing reduced test cases](https://css-tricks.com/reduced-test-cases/) might help.

**Comment by TimeForAChange** [comment]
I removed most of the strings that are tested because that's "noise":

```javascript
'use strict';

const chai = require('chai');
const expect = chai.expect;

// http://chaijs.com/plugins/chai-as-promised
const chaiAsPromised = require('chai-as-promised');
chai.use(chaiAsPromised);

const MicrodataExploder = require('../lib/microdata-exploder.js');

describe('Microdata Exploder tests', function () {

    it('should convert imploded JS "Email" object to microdata', function () {
        expect(
            MicrodataExploder.explode([
                '<span itemscope itemtype="http://gecko.io/Email">',
                '</span>'
            ].join(''))
        ).to.be.an('object').and.deep.equal({
            // The main Email microdata and its hash
            '8fca5b179df4becd89150c7684c2b63210895a155e76330f7b87868d916e4b7d': [
                '<span itemscope itemtype="http://gecko.io/Email">',
                '</span>'
            ].join('')
        });
    });

    it('should convert imploded JS "Email" object to microdata and store it', function () {
        return expect(
            MicrodataExploder.explodeAndStore([
                '<span itemscope itemtype="http://gecko.io/Email">',
                '</span>'
            ].join(''))
        ).to.eventually.be.fulfilled.and.equal([
            '8fca5b179df4becd89150c7684c2b6320895a155e76330f7b87868d916e4b7d'
        ]);
    });
});
```

**Comment by keithamus** [comment]
@TimeForAChange are you able to reproduce the error with code we could run on our own machines? The above example I don't have the `MicrodataExplorer` object and so I can't run it on my machine.

**Comment by keithamus** [comment]
Also @TimeForAChange what Promise library are you using? Or are you using a version of iojs?

**Comment by TimeForAChange** [comment]
```javascript
'use strict';

const chai = require('chai');
const expect = chai.expect;

// http://chaijs.com/plugins/chai-as-promised
const chaiAsPromised = require('chai-as-promised');
chai.use(chaiAsPromised);

describe('Dummy tests', function () {

    it('should produce an error with context and line number and does', function () {
        expect(null).to.be.an('object').and.deep.equal({foo:1, bar:2});
    });

    it('should produce an error with context and line number but does not', function () {
        return expect(
            (function() {
                return new Promise((/**Function*/ resolve, /**Function*/ reject) => {
                    reject(new Error());
                });
            })()
        ).to.eventually.be.fulfilled.and.equal('dummy');
    });

});
```

**Comment by keithamus** [comment]
@TimeForAChange ok great. Last few questions: What version of mocha are you using? What version of chai? What version of chai-as-promised?

**Comment by TimeForAChange** [comment]
mocha@2.2.5, chai@3.2.0, chai-as-promised@5.1.0

**Comment by techniq** [comment]
I'm experiencing the same issue with no context on failed chai assertions when using chai-as-promised (worked fine with regular chai).  I'm moved to using co-mocha/yielded promises and regular chai and thus works good for me.

**Comment by vdh** [comment]
@keithamus I've found this issue is also affecting `rejectedWith` when expecting a different error type or error message.

```js
it('should produce an error with context and line number but does not', function () {
  return expect(
    (function () {
      return new Promise(function () {
        throw new Error('bar');
      });
    })()
  ).to.be.rejectedWith(Error, 'foo');
});
```

**Comment by jurko-gospodnetic** [comment]
Here's a clear example reproducing the problem:

```
var chai = require('chai');
var expect = chai.expect;
var when = require('when');

chai.use(require('chai-as-promised'));

it('manually handled promise result', function () {
  return when()
    .then(function () {
      return when(42);
    })
    .then(function (x) {
      expect(x).to.deep.equal('fail-fail-fail');
    })
  ;
});

it('promise result handled using chai-as-promised', function () {
  return when()
    .then(function () {
      return expect(when(42)).to.become('fail-fail-fail');
    })
  ;
});
```

Here is the relevant dependency version information:

```
jurko@linux-dev:~/src/project$ node --version
v0.12.7
jurko@linux-dev:~/src/project$ npm --version
2.11.3
jurko@linux-dev:~/src/project$ npm list chai chai-as-promised mocha when
project@0.0.1 /home/jurko/src/project
├── chai@3.5.0 
├── chai-as-promised@5.3.0 
├── mocha@2.2.5 
└── when@3.7.3 
```

And here are the results of running that example on my machine:

```
jurko@linux-dev:~/src/project$ node_modules/.bin/mocha aaa.js 


  1) manually handled promise result
  2) promise result handled using chai-as-promised

  0 passing (24ms)
  2 failing

  1)  manually handled promise result:
     AssertionError: expected 42 to deeply equal 'fail-fail-fail'
      at aaa.js:13:25

  2)  promise result handled using chai-as-promised:
     AssertionError: expected 42 to deeply equal 'fail-fail-fail'
```

As you can see there are two failing test cases in that test script example, the first not using `chai-as-promised` and the second one using it (more precisely, using its `.to.become` matcher). And the first one reports the failing test's code location, while the second one does not.

If I bump up the `mocha` version to `2.4.5`, I get a bit more detailed stack trace output from it, which shows more clearly which part of the stack trace got lost by `chai-as-promised`:

```
jurko@linux-dev:~/src/project$ npm list chai chai-as-promised mocha when
project@0.0.1 /home/jurko/src/project
├── chai@3.5.0 
├── chai-as-promised@5.3.0 
├── mocha@2.4.5 
└── when@3.7.3 

jurko@linux-dev:~/src/project$ node_modules/.bin/mocha aaa.js 


  1) manually handled promise result
  2) promise result handled using chai-as-promised

  0 passing (41ms)
  2 failing

  1)  manually handled promise result:
     AssertionError: expected 42 to deeply equal 'fail-fail-fail'
      at assertEqual (node_modules/chai/lib/chai/core/assertions.js:485:19)
      at ctx.(anonymous function) (node_modules/chai/lib/chai/utils/addMethod.js:41:25)
      at doAsserterAsyncAndAddThen (node_modules/chai-as-promised/lib/chai-as-promised.js:296:33)
      at null.<anonymous> (node_modules/chai-as-promised/lib/chai-as-promised.js:255:21)
      at ctx.(anonymous function) [as equal] (node_modules/chai/lib/chai/utils/overwriteMethod.js:49:33)
      at aaa.js:13:25
      at tryCatchReject (node_modules/when/lib/makePromise.js:845:30)
      at runContinuation1 (node_modules/when/lib/makePromise.js:804:4)
      at Fulfilled.when (node_modules/when/lib/makePromise.js:592:4)
      at Pending.run (node_modules/when/lib/makePromise.js:483:13)
      at Scheduler._drain (node_modules/when/lib/Scheduler.js:62:19)
      at Scheduler.drain (node_modules/when/lib/Scheduler.js:27:9)

  2)  promise result handled using chai-as-promised:
     AssertionError: expected 42 to deeply equal 'fail-fail-fail'
      at assertEqual (node_modules/chai/lib/chai/core/assertions.js:485:19)
      at ctx.(anonymous function) (node_modules/chai/lib/chai/utils/addMethod.js:41:25)
      at node_modules/chai-as-promised/lib/chai-as-promised.js:308:26
      at tryCatchReject (node_modules/when/lib/makePromise.js:845:30)
      at runContinuation1 (node_modules/when/lib/makePromise.js:804:4)
      at Fulfilled.when (node_modules/when/lib/makePromise.js:592:4)
      at Pending.run (node_modules/when/lib/makePromise.js:483:13)
      at Scheduler._drain (node_modules/when/lib/Scheduler.js:62:19)
      at Scheduler.drain (node_modules/when/lib/Scheduler.js:27:9)
```

**Comment by rcollette** [comment]
I'm not sure if this is the same issue but I use `.eventually.equal(someValue)` I don't see any output in the console about what the value was and what is should have been.   It makes debugging the issue more difficult.
