### ISSUE TITLE
Problems with using chai-as-promised in es6

### ISSUE THREAD

**Issue by sztanko** [domenic/chai-as-promised#133]
Hello! Thank you for creating this wonderful library!

I am trying to use it in my tests in ES6 and I am running into the following error:

Consider the following ES6 code:
```es6
import * as chai from 'chai';
import * as chaiAsPromised from 'chai-as-promised';

chai.use(chaiAsPromised);
```

With the help of ```./node_modules/babel-cli/bin/babel.js test/t.js``` that translates to the following code:
```javascript
'use strict';

var _chai = require('chai');

var chai = _interopRequireWildcard(_chai);

var _chaiAsPromised = require('chai-as-promised');

var chaiAsPromised = _interopRequireWildcard(_chaiAsPromised);

function _interopRequireWildcard(obj) { if (obj && obj.__esModule) { return obj; } else { var newObj = {}; if (obj != null) { for (var key in obj) { if (Object.prototype.hasOwnProperty.call(obj, key)) newObj[key] = obj[key]; } } newObj.default = obj; return newObj; } }

chai.use(chaiAsPromised);
```

But piping it to node ```./node_modules/babel-cli/bin/babel.js test/feeds/t.js | node``` results in error:
```
./node_modules/chai/lib/chai.js:40
    fn(this, util);
    ^

TypeError: fn is not a function
    at Object.exports.use (./node_modules/chai/lib/chai.js:40:5)
    at [stdin]:13:6
    at Object.exports.runInThisContext (vm.js:54:17)
    at Object.<anonymous> ([stdin]-wrapper:6:22)
    at Module._compile (module.js:425:26)
    at node.js:587:27
    at doNTCallback0 (node.js:428:9)
    at process._tickCallback (node.js:357:13)
```

Can you please tell me what am I doing wrong?

**Comment by domenic** [comment]
Use require() instead of import. Chai as Promised does not support Babel modules, although it will support ES6 modules once they become a standard. If you want to make it work with Babel modules in the meantime, you'll need to ask the Babel folks for help, since it isn't a supported scenario here.

**Comment by sztanko** [comment]
Actually it looks like I got it working in the following way:

```es6
import chaiAsPromised from 'chai-as-promised';
chai.use(chaiAsPromised);
```

Are you fine for me to add this to documentation?

**Comment by domenic** [comment]
No, as I said, Babel modules are not a supported scenario.

**Comment by domenic** [comment]
Because it will likely be inaccurate when real ES6 modules land in Node. If you want documentation on how to use Babel, you need to go to the Babel website.

**Comment by c0b** [comment]
I'm using a convenience module

https://gitlab.com/c0b/promise-queue/blob/master/use-chai-as-promised.js

```javascript
import chai from 'chai';
chai.should();
import chaiAsPromised from 'chai-as-promised';
chai.use(chaiAsPromised);
```

then in the actual testing code, I can call as `import 'use-chai-as-promised.js'`, this is inspired from http://chaijs.com/guide/styles/#using-should-in-es2015 says can use `import 'chai/should';` for a **cleaner look**, would you like a similar cleaner call for chai-as-promised ?

**Comment by domenic** [comment]
No; I find that cleaner looks that are not standards-compliant, but instead just what some transpiler decided on, have a habbit of causing problems in the future.

**Comment by djKianoosh** [comment]
How's this:
```
import chai from 'chai';
import chaiAsPromised from 'chai-as-promised';
chai.use(chaiAsPromised);
const should = chai.should();
const {expect, assert} = chai;

// then later on:
    it('should eventually return data', (done) => {
      somethingThatAsyncFetches().should.eventually.have.property('list').notify(done);;
    });
```

**Comment by colinskow** [comment]
With TypeScript 2.54 I had to do it like this to get it working:

```ts
import * as chai from 'chai';
import * as chaiAsPromised from 'chai-as-promised';

chai.use(chaiAsPromised);
```

**Comment by trajano** [comment]
@colinskow 
the code works on the IDE and it compiles, but fails on protractor
```
$ protractor ./protractor.config.js 
[02:26:12] I/launcher - Running 1 instances of WebDriver
[02:26:12] I/local - Starting selenium standalone server...
[02:26:13] I/local - Selenium standalone server started at http://192.168.56.1:56903/wd/hub
[02:26:20] E/launcher - Error: TypeError: fn is not a function
    at Object.exports.use (D:\dh\app\node_modules\chai\lib\chai.js:39:5)
    at Object.<anonymous> (D:\dh\app\e2e\login.spec.ts:5:1)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Module.m._compile (D:\dh\app\node_modules\ts-node\src\index.ts:382:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Object.require.extensions.(anonymous function) [as .ts] (D:\dh\app\node_modules\ts-node\src\index.ts:385:12)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
[02:26:20] E/launcher - Process exited with error code 100
```
So there may be something else to watch out for.

**Comment by wagolemusa** [comment]
Make sure You install  
**npm install chai-as-promised**  
it will help
