### ISSUE TITLE
`rejectedWith` with boolean values

### ISSUE THREAD

**Issue by kittaakos** [domenic/chai-as-promised#186]
Hey there,

I am experiencing an odd behavior when checking promise rejection. It seems, that the rejected boolean value is simply ignored. I would expect three failing test cases including the `rejects as promised (boolean)` one but I get only two. (Please see console output below). Maybe I am doing something wrong. Probably, one can easily spot the problem. I look forward to any kind of feedbacks. Cheers.

Here is my setup:

`/src/foo.spec.ts`:
```
import "mocha";
import * as chai from "chai";
import * as chaiAsPromised from "chai-as-promised";

const expect = chai.expect;

before(function() {
    chai.config.showDiff = true;
    chai.config.includeStack = true;
    chai.use(chaiAsPromised);
    chai.should();
});

describe('bar', function() {

    it('resolves as promised', function () {
        // That is fine.
        return expect(Promise.resolve('woof')).to.eventually.equal('woof');
    });

    it('rejects as promised (string)', function () {
        // That is reported as an error. Works fine.
        return expect(Promise.reject('caw')).to.eventually.be.rejectedWith('caw2');
    });

    it('rejects as promised (boolean)', function () {
        // !!! That is also fine but should *not* be, right?
        return expect(Promise.reject(false)).to.eventually.be.rejectedWith(true);
    });

    it('rejects as promised (Error)', function () {
        // That fails as well and reported as an error which seems to be reasonable.
        return expect(Promise.reject(false)).to.eventually.be.rejectedWith(Error);
    });

});
```

`test/mocha.opts`:
```
--require ts-node/register
--reporter spec
--watch-extensions ts
src/**/*.spec.ts
```

`tsconfig.json`:
```
{
  "compilerOptions": {
    "declaration": true,
    "noImplicitAny": true,
    "noEmitOnError": true,
    "strictNullChecks": true,
    "module": "commonjs",
    "moduleResolution": "node",
    "target": "es5",
    "lib": ["es6", "dom"],
    "outDir": "lib",
    "sourceMap": true
  },
  "include": [
    "src"
  ]
}
```

`package.json`:
```
{
  "name": "tmp",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "./node_modules/.bin/mocha --watch"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@types/chai": "^3.4.35",
    "@types/chai-as-promised": "0.0.30",
    "@types/mocha": "^2.2.40",
    "chai": "^3.5.0",
    "chai-as-promised": "^6.0.0",
    "mocha": "^3.2.0",
    "ts-node": "^3.0.0",
    "typescript": "^2.2.1"
  }
}
```

Console output when running the tests:
```
bar
  ✓ resolves as promised
  1) rejects as promised (string)
  ✓ rejects as promised (boolean)
  2) rejects as promised (Error)


2 passing (56ms)
2 failing

1) bar rejects as promised (string):
   AssertionError: expected promise to be rejected with an error including 'caw2' but got 'caw'
    at node_modules/chai-as-promised/lib/chai-as-promised.js:212:30
    at runMicrotasksCallback (internal/process/next_tick.js:58:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

2) bar rejects as promised (Error):
   AssertionError: expected promise to be rejected with 'Error' but it was rejected with false
    at node_modules/chai-as-promised/lib/chai-as-promised.js:203:30
    at runMicrotasksCallback (internal/process/next_tick.js:58:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by domenic** [comment]
Can you edit your example to be in JavaScript? I'm not interested in debugging other languages.

**Comment by kittaakos** [comment]
@domenic I have updated my initial comment. Please let me know if I need to change anything else. Thanks in advance!

**Comment by keithamus** [comment]
Firstly, I'm not sure of the intent of your code, but you should absolutely be rejecting with only `Error` instances, or subclass instances such as `TypeError`. rejecting Promises with strings or booleans is an anti-pattern. 

Secondly, the reason this is not working correctly is because `rejectedWith` has a few type signatures, but none that support `boolean` properties. It's a bug that it is passing with a boolean, but it is also a misuse of the `rejectedWith` API to pass a boolean. The signatures are `rejectedWith(ErrorConstructor)`, `rejectedWith(ErrorConstructor, 'stringMessage')`, `rejectedWith('stringMessage')`, `rejectedWith(/regExpMessage/)`. Coincidentally, with a boolean as the first argument, the function manages to fall through all of the control flow logic we have. 

For a fix to this, I suggest we ensure that `errorLike` in the assertion ([here](https://github.com/domenic/chai-as-promised/blob/b2cfbdc71360dad1faaa29f64bcc8ba54819084e/lib/chai-as-promised.js#L130)) is checked to ensure it is one of the expected types (`function`, `string`, `regexp`), and if it isn't then we should throw some kind of error describing how to use the rejectedWith function correctly.

**Comment by kittaakos** [comment]
> rejecting Promises with strings or booleans is an anti-pattern.

I was not aware of this. Thanks for the explanation on this ticket!

**Comment by domenic** [comment]
@keithamus Thanks so much for your help here and for digging into things.

Does Chai throw such an error if you pass it a boolean to `.throws()`?

**Comment by keithamus** [comment]
@domenic Short answer: no. Longer answer: right now there is virtually no type checking inside chai. We are slowly doing this, and hopefully this will hopefully change to be enforced in future (see https://github.com/chaijs/chai/issues/585). We can put this as a ticket in Chai to get it in for Chai@4 if you'd like us to fall in line with this plugin.
