### ISSUE TITLE
TypeError: 'caller', 'callee', and 'arguments' properties may not be accessed on strict mode

### ISSUE THREAD

**Issue by ankurkaushal** [domenic/chai-as-promised#210]
I have been trying to use `chai-as-promised` to test `fetch` calls but haven't been able to get the expected result.

Here's the `ES6` module I am testing: 

```
export class Weather {
    /**
     * Constructor for Weather class
     *
     * @param latitude
     * @param longitude
     */
    constructor(latitude, longitude) {
        this.latitude = latitude;
        this.longitude = longitude;
    }

    /**
     * Fetches the weather using API
     */
    getWeather() {
        let headers = new Headers();

        let init = {
            method: 'GET',
            headers: headers,
            cache: 'default'
        };

        let url = 'http://localhost:8080/weather?lat=' + this.latitude + '&lon=' + this.longitude;

        return fetch(url, init).then(function (response) {
            return response.json();
        });
    }
}
```

Here's the test:

```
import {Weather} from '../js/weather';
import chai from 'chai';
import sinon from 'sinon';
import * as chaiAsPromised from 'chai-as-promised';

chai.use(chaiAsPromised);

let assert = chai.assert;

describe('weatherbot', function () {
    beforeEach(() => {
        sinon.stub(window, 'fetch');

        let data = '{"coord":{"lon":-79.73,"lat":43.66},"weather":[{"id":521,"main":"Rain","description":"shower rain","icon":"09d"}],"base":"stations","main":{"temp":15.28,"pressure":1009,"humidity":82,"temp_min":13,"temp_max":17},"visibility":24140,"wind":{"speed":7.2,"deg":30},"clouds":{"all":90},"dt":1496770020,"sys":{"type":1,"id":3722,"message":0.0047,"country":"CA","sunrise":1496741873,"sunset":1496797083},"id":5907364,"name":"Brampton","cod":200}';
        let res = new window.Response(data, {
            status: 200,
            headers: {
                'Content-type': 'application/json'
            }
        });

        window.fetch.returns(Promise.resolve(res));
    });

    afterEach(() => {
        window.fetch.restore();
    });

    it('should return a resolved promise if call is successful', () => {
        let weather = new Weather(43.65967339999999, -79.72506369999999);

        return assert.isFulfilled(weather.getWeather(), "promise resolved");
    });
});
```

I am running running the test using `karma` & been getting this error:

```
TypeError: 'caller', 'callee', and 'arguments' properties may not be accessed on strict mode functions or the arguments objects for calls to them
	    at Assertion (test/index.js:835:73)
	    at Function.assert.isFulfilled (test/index.js:625:187)
	    at Context.<anonymous> (test/index.js:6829:2334)
```
Also, I am using `babel-cli` and `webpack` as well.

Firstly, why this error being thrown & second, am I doing something wrong in my test?

**Comment by domenic** [comment]
Sorry, I can't debug issues like this where there are so many third party packages involved. Please produce a minimal example I can run using node example.js andno webpack or Babel or Sinon or syntax that isn't supported in major engines.

**Comment by ankurkaushal** [comment]
Looks like it was my bad, I was using the wrong assertion, using  `return weather.getWeather().should.be.fulfilled;` seems to fix the issue.

I will close the issue. Thank you for the quick reply @domenic, I really appreciate it.
