### ISSUE TITLE
chai-fs impacts promise handling when loaded after chai-as-promised

### ISSUE THREAD

**Issue by deployable** [domenic/chai-as-promised#218]
When using both chai-fs and [chai-as-promised](https://github.com/domenic/chai-as-promised) promises start returning before being handled, kind of like when you run an async test without `done`.

I'm not sure which side the issues sits with so have raised it on both

Example test:
```
const chai = require('chai')
const expect = chai.expect
chai.should()
chai.use(require('chai-as-promised'))
chai.use(require('chai-fs'))

describe('resolve', function(){

  it('expect', function(){
    return expect( Promise.resolve('two') ).to.eventually.equal('one')
  })

  it('should', function(){
    return Promise.resolve('two').should.eventually.equal('one')
  })

})       
```
Results in promises being rejected but not handled by mocha:
```
○ → mocha

  resolve
    ✓ shouldn't resolve
(node:79302) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): AssertionError: expected 'two' to equal 'one'
    ✓ shouldn't resolve
(node:79302) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): AssertionError: expected 'two' to equal 'one'


  2 passing (16ms)
```

Swapping the order and loading `chai-fs` first:
```
chai.use(require('chai-fs'))
chai.use(require('chai-as-promised'))
```
Results in the normal promise handling behaviour:
```
○ → mocha

  resolve
    1) expect
    2) should


  0 passing (16ms)
  2 failing

  1) resolve expect:

      AssertionError: expected 'two' to equal 'one'
      + expected - actual

      -two
      +one
      
      at getBasePromise.then.then.newArgs (node_modules/chai-as-promised/lib/chai-as-promised.js:302:22)

  2) resolve should:

      AssertionError: expected 'two' to equal 'one'
      + expected - actual

      -two
      +one
      
      at getBasePromise.then.then.newArgs (node_modules/chai-as-promised/lib/chai-as-promised.js:302:22)
```

**Comment by deployable** [comment]
https://github.com/chaijs/chai-fs/issues/38

**Comment by BadIdeaException** [comment]
Sorry to necromance, but having run into this exact same issue today, I think the caveat about needing to be `chai.use`d last should be made way more prominent in the readme. As it is, it's kind of hidden far down, and easy to miss.

Love this package! I use it on pretty much all of my projects.
