### ISSUE TITLE
await not working as advertised

### ISSUE THREAD

**Issue by budleigh** [domenic/chai-as-promised#229]
Hi there - feel like a bit of an idiot, been staring at this for nearly an hour.

```
            it('fails', async function () {
                expect(await UserInterface.newUser({
                    email: 'test@test.com',
                    password: 'anotherpassword',
                })).to.be.rejectedWith(MongoError);
            });
```

fails to capture the error: 

```
    .newUser
         when the user already exists
           fails:
     MongoError: E11000 duplicate key error collection: huang_test.users index: email_1 dup key: { : "test@test.com" }
      at Function.MongoError.create (node_modules\mongodb-core\lib\error.js:31:11)
      at toError (node_modules\mongodb\lib\utils.js:139:22)
      at node_modules\mongodb\lib\collection.js:668:23
      at handleCallback (node_modules\mongodb\lib\utils.js:120:56)
      at node_modules\mongodb\lib\bulk\unordered.js:465:9
      at handleCallback (node_modules\mongodb\lib\utils.js:120:56)
      at resultHandler (node_modules\mongodb\lib\bulk\unordered.js:413:5)
      at node_modules\mongodb-core\lib\connection\pool.js:469:18
      at _combinedTickCallback (internal/process/next_tick.js:131:7)
      at process._tickCallback (internal/process/next_tick.js:180:9)
```

The docs are pretty straightforward here, so I assume it's something I'm doing wrong.

**Comment by meeber** [comment]
@budleigh I think you just need to pull `await` out of `expect`:

```js
await expect(Promise.reject(new TypeError())).to.be.rejectedWith(TypeError);
```

**Comment by leomelzer** [comment]
@meeber Thanks! Just had the same issue. Pulling `await` out works for me.
