### ISSUE TITLE
expect to be rejected with a property

### ISSUE THREAD

**Issue by piotr-s-brainhub** [domenic/chai-as-promised#236]
it's probably a feature request but I write my environment details because maybe it's a bug

Node version: 8.6.0
npm version: 5.2.0
chai-as-promised version: 7.1.1
chai version: 4.1.2

I have the following code:
```
const chai = require('chai');
const chaiAsPromised = require('chai-as-promised');

chai.use(chaiAsPromised);

const expect = chai.expect;

const error = new Error;
error.foo = 123;

expect(Promise.reject(error)).to.be.rejectedWith(Error, { foo: 123 });
```

Actual behavior:
```
(node:51977) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): AssertionError: expected promise to be rejected with an error including { foo: 123 } but got ''
(node:51977) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Expected behavior:
```
```

Of cource if the rejected error doesn't have the expected field or its field has another value, it should fail.

**Comment by piotr-s-brainhub** [comment]
It also doesn't work:
```
const chai = require('chai');
const chaiAsPromised = require('chai-as-promised');

chai.use(chaiAsPromised);

const expect = chai.expect;

const error = new Error;
error.foo = 123;

expect(Promise.reject(error)).to.be.rejectedWith(Error).and.have.property('foo', 123);
```
I obtain:
```
/Users/piotr.sroczkowski/brainhub/dmx/npm-dmx-sdk/node_modules/chai/lib/chai/assertion.js:141
      throw new AssertionError(msg, {
      ^
AssertionError: expected {} to have property 'foo'
    at Object.<anonymous> (/Users/piotr.sroczkowski/brainhub/dmx/npm-dmx-sdk/1.js:11:66)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Function.Module.runMain (module.js:665:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:607:3
```

**Comment by piotr-s-brainhub** [comment]
It works when I add `.eventually`
so such a test succeeds:
```
const chai = require('chai');
const chaiAsPromised = require('chai-as-promised');

chai.use(chaiAsPromised);

const expect = chai.expect;

const error = new Error;
error.foo = 123;

expect(Promise.reject(error)).to.be.eventually.rejectedWith(Error).and.have.property('foo', 123);
```

Therefore IMO you should improve README because nowhere I can see `.eventually.rejectedWith`.

**Comment by samcodrington** [comment]
I didn't find that eventually resolved my problem with the following specs
Node version: 10.6.0
npm version: 6.1.0
chai-as-promised version: 7.1.1
chai version: 4.1.2
--posting here so there's a solution as this is a major problem
given the following test
```
var chaiAsPromised = require("chai-as-promised");
var chai = require("chai");
chai.use(chaiAsPromised);

var should = chai.should();
var expect = chai.expect;
var asyncFunc = async function(){
  return true;
}
it("Async function should throw error", () => {
	expect(asyncFunc()).to.be.rejected; //should fail
});
```
This function passes with 
```
  ✓ Async function should throw error
(node:11142) UnhandledPromiseRejectionWarning: AssertionError: expected promise to be rejected but it was fulfilled with true
(node:11142) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:11142) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

  1 passing (12ms)
```

and can be fixed by using *await* keyword on the expect function!
```
it("Async function should throw error", async () => {
	await expect(asyncFunc()).to.be.rejected;
});
```
Now returns:
```
 1) Async function should throw error

  0 passing (12ms)
  1 failing

  1) Async function should throw error:
     AssertionError: expected promise to be rejected but it was fulfilled with true
```
Not entirely sure why this is the case, I think it might be failing due to the way .to.be.rejected() wraps the function in a Promise.

**Comment by Ceesjansen** [comment]
@piotr-s-brainhub 

Hi, just tested your solution and I can confirm it works, thank you! And I agree with updating the docs :)

**Comment by piotr-s-brainhub** [comment]
@Ceesjansen 

Anyway now you can use `async/ await` so `chai-as-promised` is no longer needed.

**Comment by unicornist** [comment]
this works too:
```javascript
expect(Promise.reject).to.be.rejectedWith(Error).eventually.with.property('name', 'YourError')
```
