### ISSUE TITLE
assert.isFulfilled doesn't works with native Promise.all

### ISSUE THREAD

**Issue by vxcamiloxv** [domenic/chai-as-promised#241]
I have some code like: 

```javascript
     return Promise.all([
            assert.isFulfilled(promise),
            assert.eventually.nestedInclude(promise, { "fields.name": "server" }),
            assert.eventually.nestedInclude(promise, { "streams[0].path": "/dev/null" }),
            assert.eventually.nestedInclude(promise, { "streams[0].level": 30 })
       ]);
```
With bluebird works fine but with native es6 Promise was broken and returned:
```
Error: Invalid Chai property: _promiseConstructor
      at Object.proxyGetter [as get] (node_modules/chai/lib/chai/utils/proxify.js:66:17)
      at Object.ES.IsPromise (node_modules/es6-shim/es6-shim.js:1579:20)
      at Function.resolve (node_modules/es6-shim/es6-shim.js:1857:16)
      at Function.all (node_modules/es6-shim/es6-shim.js:1803:33)
      at Context.<anonymous> (src/server/helpers/logger/logger.spec.js:56:24)
```

- node: 8.8.3
- OS: Gnu/Linux (debian)
- chai: 4.1.2
- chai-as-promised: 7.1.1
- mocha: 5.0.1

**Comment by meeber** [comment]
@vxcamiloxv Based on your stack trace, the problem looks to be a conflict between the `es6-shim` module and Chai core's proxy protection feature (which detects when unrecognized properties are accessed on a Chai assertion object to prevent typo-related problems like `expect(true).to.ture;`).

You can try adding this at the top of your test file:

```js
chai.config.proxyExcludedKeys.push('_promiseConstructor');
```

**Comment by vxcamiloxv** [comment]
@meeber  works :+1:
