### ISSUE TITLE
UnhandledPromiseRejectionWarning: Unhandled promise rejection.

### ISSUE THREAD

**Issue by Hirurg103** [domenic/chai-as-promised#255]
I have the following simple test:

```js
const chai = require('chai');
const expect = chai.expect;

const chaiAsPromised = require("chai-as-promised");
chai.use(chaiAsPromised);

describe("Promises", () => {
  context("comparing promise resolved with 2 with number 3", () => {
    it("should fail", () => {
      expect(Promise.resolve(2)).to.eventually.equal(3);
    });
  });
});
```

When I run it with `npm test -- --grep 'should fail'` the test passes with 

```
> NODE_ENV=test NODE_PATH=./test:./src mocha test/**/*_spec.js "--grep" "should fail"



  Promises
    comparing promise resolved with 2 with number 3
      ✓ should fail
(node:8072) UnhandledPromiseRejectionWarning: AssertionError: expected 2 to equal 3
    at getBasePromise.then.then.newArgs (/Users/hirurg103/Documents/work/alerts/node_modules/chai-as-promised/lib/chai-as-promised.js:302:22)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
(node:8072) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:8072) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.


  1 passing (13ms)
```

I use the following package versions:

mocha@3.5.3
chai@4.2.0
chai-as-promised@7.1.1

and node v11.6.0

This test case should fail, but it passes.
What am I doing wrong in this test?

**Comment by meeber** [comment]
Gotta [return the promise to your test runner](https://mochajs.org/#working-with-promises):

```js
describe("Promises", () => {
  context("comparing promise resolved with 2 with number 3", () => {
    it("should fail", () => {
      return expect(Promise.resolve(2)).to.eventually.equal(3);
    });
  });
});
```

**Comment by Hirurg103** [comment]
ah, got it! Many thanks @meeber
